### PR TITLE
refactor(MBeanTree): refactored code so both JMX and camel components have the same search behaviour

### PR DESCRIPTION
**Pull request by joshiraez**
The logic should work but as in https://github.com/hawtio/hawtio-next/pull/160 I'm unable to get yarn start to start the instance after build finishes successfully so I couldn't do a final test. I'm setting it up as a draft and will continue in Tuesday

### CODE REVIEW

**Review by tadayosi — APPROVED** [review]
lgtm

**Review by phantomjinx — APPROVED** [review]
LGTM

**Comment by tadayosi** [comment]
I think it's good. Let's merge it.

**Comment by joshiraez** [comment]
Thank you tadayoshi. I thought I had already merged it when I put that
comment before and I just forgot about it. My bad :(. Thank you for picking
this up

**Pull request merged**
